# Generated by Django 5.2.5 on 2025-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_product_picture_product_specfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DurationField()),
                ('code', models.TextField(blank=True, null=True)),
                ('link', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='product')),
                ('specfile', models.FileField(blank=True, null=True, upload_to='specfile')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
