# Generated by Django 5.2.5 on 2025-08-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inslock',
            field=models.BooleanField(default=True),
        ),
    ]
